kind: HTTPChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: $name
spec:
  selector:
    namespaces:
      - $namespace
    labelSelectors:
      app: $app
  mode: $mode
  target: Request
  delay: $delay
  port: $port
  path: '*'
  duration: $duration