logs:
  dir: ./logs/run_info/
  format: "%(asctime)s - %(pathname)s[line:%(lineno)d] - %(levelname)s - %(message)s"

records:
  dir: ./records/
  chaosmesh_records: http://10.176.122.154:30331/api/events  # chaosmesh events query url

injection:
  metadata:
    st_time: 2023-02-09 17:00:00  # start time of all fault injection tasks
    namespace: default  # train-ticket deployment namespace
    chaosmesh:
      tmp_dir: ./command/chaos_mesh/tmp/  # tmp dir to store the generated yaml files.
      kinds:
        - HTTPChaos
    faults:  # must inject api faults first because of bugs in chaos-blade
      - pod-typed-mysql-delay  # chaos-blade
      - pod-rabbitmq-delay  # chaos-blade
  spec:
    pod-typed-mysql-delay:
      info:
        duration: 300  # (s) duration of each fault
        interval: 300  # (s) interval between two adjacent faults
        time: 500  # (ms) delay time
      targets: # pod_prefix sqltype(insert|delete|update|select)
        - ts-food-service insert
        # - ts-order-service insert
        # - ts-route-service insert
        - ts-auth-service delete
        # - ts-station-service delete
        # - ts-travel-service delete
        - ts-config-service update
        # - ts-order-other-service update
        # - ts-travel-service update
        - ts-assurance-service select
        # - ts-price-service select
        # - ts-train-food-service select
    pod-rabbitmq-delay:
      info:
        duration: 300  # (s) duration of each fault
        interval: 300  # (s) interval between two adjacent faults
        time: 500  # (ms) delay time
      targets:  # pod_prefix
        - ts-food-service
    